package org.acme;

import io.grpc.ManagedChannelBuilder;

//Generated by protoc
import org.acme.service.WeatherServiceGrpc;
import org.acme.grpc.Dto.CurrentWeatherRequest;
//

public class WeatherClient {

    public static void main(String[] args) {

        var address = "localhost:30002";

        var channel = ManagedChannelBuilder.forTarget(address)
                .usePlaintext()
                .build();

        var client = WeatherServiceGrpc.newBlockingStub(channel);

        var lat = Double.parseDouble("52.520008");
        var lon = Double.parseDouble("13.404954");

        var builder = CurrentWeatherRequest.newBuilder()
                .setLat(lat)
                .setLon(lon)
                .setLang("en_us");

        var request = builder.build();

        var data = client.invoke(request);

        System.out.println(data.getCity() + ", " + data.getCountry()+ ", " + data.getTemp() + "C");

    }

}
